[workspace]
resolver = "2"
members = [
    "katas/4kyu/*",
    "katas/5kyu/*",
    "katas/6kyu/*",
    "katas/7kyu/*",
    "katas/8kyu/*",
    "scratch"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["somnus"]
